[package]
name = "native_solana_counter"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
solana-program = "=3.0.0"
solana-system-interface = {version = "3.3.0", features = ["bincode"]}
borsh = {version = "1", features = ["derive"]}

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = ['cfg(feature, values("custom-heap", "custom-panic"))']
