[package]
name = "cust_fb"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "cust_fb"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []


[dependencies]
anchor-lang = "0.32.1"

[dev-dependencies]
litesvm = "0.7.1"
solana-keypair = "2.2"
solana-pubkey = "2.3"
solana-signer = "2.2"
solana-instruction = "2.3"
solana-transaction = "2.2"
solana-message = "2.3"
solana-sdk-ids = "2.2"


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(target_os, values("solana"))',
] }
